// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_appsync_graphqlEndpoint": "https://x72bi7t4ovdlterojrnechagqi.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "ap-southeast-2:f35586fb-bd38-4a59-b036-185be38d3ab7",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_eJxm0SUxn",
    "aws_user_pools_web_client_id": "1eabgqgi85o27tnr1faptr4ph7"
};


export default awsmobile;
